const {chromium}=require(process.argv[2]||'playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const root=path.resolve(__dirname,'..'),out=root+'/docs/out',pkg='/Users/amir/Desktop/Alashi Presentation';
(async()=>{const opened=process.argv.includes('--open'),browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:!opened,args:['--window-size=1280,800','--autoplay-policy=no-user-gesture-required']});let leave=false;try{const page=await browser.newPage({viewport:opened?null:{width:1920,height:1080},deviceScaleFactor:opened?undefined:1}),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url())});
 if(process.argv.includes('--assets')){await page.goto('file://'+root+'/app/alashi-parallel-demo.html?capture=1');await page.waitForFunction(()=>!!window.Parallel);const png=await page.evaluate(()=>{const homes=StudioWorld.homes.map(h=>[...h]);archive.agents.forEach((a,i)=>StudioWorld.homes[i]=homes[Parallel.participants.indexOf(a.name)]);Parallel.render(14);const src=StudioWorld.renderer.domElement,f=Parallel.fullMapFrame(),c=document.createElement('canvas');c.width=1920;c.height=1080;const g=c.getContext('2d');g.fillStyle='#09131c';g.fillRect(0,0,1920,1080);const scale=Math.min(1840/f.sw,1000/f.sh),w=f.sw*scale,h=f.sh*scale;g.drawImage(src,f.sx,f.sy,f.sw,f.sh,(1920-w)/2,(1080-h)/2,w,h);return c.toDataURL('image/png').split(',')[1]});fs.writeFileSync(root+'/assets/slides/board-overview.png',Buffer.from(png,'base64'));console.log('Clean full-board asset ready');return}
 await page.goto('file://'+(opened?pkg+'/Alashi.html':root+'/docs/deck.html')+(opened?'':'?capture=1'));await page.evaluate(()=>document.fonts.ready);await page.waitForFunction(()=>!!window.Deck);assert.equal(await page.locator('.slide').count(),11);if(opened){await page.evaluate(()=>Deck.show(0));await page.bringToFront();leave=true;console.log('Presentation opened on title slide');await new Promise(r=>browser.on('disconnected',r));return}
 const overflows=[];for(let i=0;i<11;i++){await page.evaluate(i=>Deck.show(i),i);const o=await page.locator('.slide.active .text').evaluateAll(ns=>ns.filter(n=>n.scrollHeight>n.clientHeight+2||n.scrollWidth>n.clientWidth+2).map(n=>({text:n.textContent,scroll:[n.scrollWidth,n.scrollHeight],box:[n.clientWidth,n.clientHeight]})));if(o.length)overflows.push({slide:i+1,items:o});if(!opened)await page.screenshot({path:out+'/slide-'+String(i+1).padStart(2,'0')+'.png'})}assert.deepEqual(overflows,[]);
 await page.evaluate(()=>Deck.show(8));await page.waitForFunction(()=>document.querySelector('video').readyState>=2);await page.evaluate(()=>document.querySelector('video').play());await page.waitForFunction(()=>{const v=document.querySelector('video');return v.currentTime>.5&&!v.paused},null,{timeout:15000});const video=await page.evaluate(()=>{const v=document.querySelector('video');return {time:v.currentTime,paused:v.paused,duration:v.duration,width:v.videoWidth}});assert.ok(video.time>.5&&!video.paused);await page.evaluate(()=>Deck.show(9));assert.ok(await page.evaluate(()=>document.querySelector('video').paused));
 if(!opened){await page.pdf({path:out+'/deck.pdf',preferCSSPageSize:true,printBackground:true});fs.copyFileSync(out+'/deck.pdf',pkg+'/Alashi.pdf');for(const [w,h] of [[1280,720],[1440,900],[1024,768]]){await page.setViewportSize({width:w,height:h});await page.evaluate(()=>Deck.show(0));const r=await page.locator('.slide.active').boundingBox();assert.ok(r.x>=-1&&r.y>=-1&&r.x+r.width<=w+1&&r.y+r.height<=h+1)}
 await page.goto('file://'+root+'/docs/deck.html');await page.evaluate(()=>document.fonts.ready);await page.locator('#next').click();assert.equal(await page.locator('.slide.active').getAttribute('data-slide'),'2');await page.keyboard.press('ArrowLeft');assert.equal(await page.locator('.slide.active').getAttribute('data-slide'),'1');await page.locator('#show-notes').click();assert.ok(await page.locator('#notes').isVisible());}
 assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);const report={slides:11,main:8,timing_seconds:300,overflows,video,errors,external_requests:requests,editable_pptx:true};fs.writeFileSync(out+'/deck_check.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
 if(opened){await page.evaluate(()=>Deck.show(0));await page.bringToFront();leave=true;console.log('Presentation opened on title slide');await new Promise(r=>browser.on('disconnected',r))}
 }finally{if(!leave)await browser.close()}})().catch(e=>{console.error('[ERROR]',e);process.exitCode=1});
