const parallelProof=__PARALLEL_PROOF__;
const participantOrder=['Aitore','Aikorkem','Aisultan','Botagul','Aibot','Zhambyl'];
const participantIndices=participantOrder.map(n=>archive.agents.findIndex(a=>a.name===n));
const stageList=[];
for(let round=1;round<=6;round++)for(const phase of ['market','action','law']){const acts=archive.actions.map((a,serial)=>({...a,serial})).filter(a=>a.round===round&&a.phase===phase);if(acts.length)stageList.push({round,phase,acts})}
const stageDuration=90/stageList.length;
for(const stage of stageList){const lo=Math.min(...stage.acts.map(a=>a.ts)),hi=Math.max(...stage.acts.map(a=>a.ts));stage.acts.forEach(a=>{a.visualStart=.3+(a.ts-lo)/(hi-lo||1)*(stageDuration-1.7)});for(let actor=0;actor<6;actor++){const queue=stage.acts.filter(a=>a.actor===actor);queue.forEach((a,i)=>{if(i)a.visualStart=Math.max(a.visualStart,queue[i-1].visualStart+.4);a.visualDuration=Math.max(.3,Math.min(1.2,(queue[i+1]?.visualStart??stageDuration)-a.visualStart-.05))})}}
const PINK='#eef4f2',PDIM='#b0c0c4',MINT='#9bdccd';
C.width=1920;C.height=1080;
function text(t,x,y,size=30,color=PINK,weight=600,align='left'){g.save();g.font=weight+' '+size+'px '+(/\d|SOL/.test(String(t))?'Menlo,monospace':'Jura,sans-serif');g.textAlign=align;g.textBaseline='middle';g.fillStyle=color;g.fillText(String(t),x,y);g.restore()}
function box(x,y,w,h,fill,r=12,stroke=null){g.save();g.beginPath();g.roundRect(x,y,w,h,r);g.fillStyle=fill;g.fill();if(stroke){g.strokeStyle=stroke;g.lineWidth=2;g.stroke()}g.restore()}
function statesAt(t){const si=Math.max(0,Math.min(stageList.length-1,Math.floor((t-18)/stageDuration))),stage=stageList[si],age=t>=108?stageDuration:Math.max(0,t-18-si*stageDuration);const states=archive.agents.map((agent,actor)=>{const queue=stage.acts.filter(a=>a.actor===actor),current=queue.filter(a=>a.visualStart<=age).at(-1),past=stageList.slice(0,si).flatMap(s=>s.acts).filter(a=>a.actor===actor),last=current||past.at(-1);const completed=!!current&&age>=current.visualStart+current.visualDuration;return {actor,name:agent.name,target:last?info[last.action][1]:null,action:current||null,last,active:!!current&&t<108,progress:current?Math.min(1,(age-current.visualStart)/current.visualDuration):1,completed,waiting:!current}});return {stage,age,states,index:si}}
function sourcePoint(i){const a=StudioWorld.agents[i].position,pt=StudioWorld.project(a.x,2,a.z);return {x:pt.x*2,y:(pt.y-130)*2}}
function sourceSite(key){const s=StudioWorld.sites[key],pt=StudioWorld.project(s.x,2.5,s.z);return {x:pt.x*2,y:(pt.y-130)*2}}
// Project a conservative box enclosing the complete plinth and all buildings.
// Every panel uses the same contain transform, never an actor-centered crop.
function fullMapFrame(image){const points=[];function bounds(x0,x1,y0,y1,z0,z1){for(const x of [x0,x1])for(const y of [y0,y1])for(const z of [z0,z1]){const p=StudioWorld.project(x,y,z);points.push({x:p.x*2,y:(p.y-130)*2})}}bounds(-15.8,15.8,-1.2,2.5,-11.2,11.2);for(const [key,s] of Object.entries(StudioWorld.sites))bounds(s.x-3.3,s.x+3.3,.3,key==='factory'||key==='law'?5.4:4.8,s.z-3,s.z+3);const sx=Math.min(...points.map(p=>p.x))-12,sy=Math.min(...points.map(p=>p.y))-12,right=Math.max(...points.map(p=>p.x))+12,bottom=Math.max(...points.map(p=>p.y))+12;return {sx,sy,sw:right-sx,sh:bottom-sy,sourceWidth:image.width,sourceHeight:image.height}}

function header(label){text('ALASHI',32,48,46);text(label,352,48,30,PDIM);text('ОДНА ПАРТИЯ / 6 АГЕНТОВ',1888,48,22,MINT,600,'right');g.fillStyle='#5d788866';g.fillRect(32,91,1856,1)}
function drawPanel(image,actor,slot,s,t,mode){const x=32+(slot%3)*624,y=112+Math.floor(slot/3)*448,w=608,h=432,color=StudioWorld.palette[actor];box(x,y,w,h,'#14232b',16,color);text(archive.agents[actor].name,x+20,y+31,36,PINK,700);text(mode==='join'?'ВХОД':mode==='final'?'ИТОГ':s.completed?(s.action.ok?'ПРИНЯТО':'ОТКАЗ'):s.active?'ДЕЙСТВУЕТ':'ОЖИДАНИЕ',x+w-20,y+31,18,s.active?color:PDIM,600,'right');let title=mode==='join'?'Собственный кошелёк и подпись':mode==='final'?'Касса и выплата после 6 раундов':s.action?info[s.action.action][0]:'Нет нового действия в этой фазе';text(title,x+20,y+70,23,PDIM);
 const mx=x+8,my=y+92,mw=w-16,mh=272,pt=sourcePoint(actor),frame=fullMapFrame(image),scale=Math.min((mw-24)/frame.sw,(mh-24)/frame.sh),dw=frame.sw*scale,dh=frame.sh*scale,ox=mx+(mw-dw)/2,oy=my+(mh-dh)/2;
 g.save();g.beginPath();g.rect(mx,my,mw,mh);g.clip();g.drawImage(image,frame.sx,frame.sy,frame.sw,frame.sh,ox,oy,dw,dh);
 const px=ox+(pt.x-frame.sx)*scale,py=oy+(pt.y-frame.sy)*scale;g.strokeStyle=color;g.lineWidth=2.5;g.beginPath();g.arc(px,py+5,12,0,Math.PI*2);g.stroke();g.fillStyle=PINK;g.beginPath();g.moveTo(px,py-5);g.lineTo(px-5,py-15);g.lineTo(px+5,py-15);g.closePath();g.fill();
 if(s.target){box(mx+8,my+8,156,28,'#0e1d26e8',6);text(StudioWorld.sites[s.target].name,mx+86,my+22,16,PINK,600,'center')}
 g.restore();
 if(mode==='join'){const p=parallelProof.players.find(p=>p.name===archive.agents[actor].name),j=parallelProof.transactions.find(j=>j.instruction==='join'&&j.receipt.transaction.message.accountKeys[0]===p.wallet);text(p.wallet,x+20,y+386,17,PDIM);text('TX CONFIRMED · SLOT '+j.receipt.slot,x+20,y+415,19,MINT)}else if(mode==='final'){text('Касса '+money(archive.final_cash[actor]),x+20,y+386,24);text('Выплата '+money(archive.payouts[actor]),x+20,y+416,24,color)}else{const a=s.action;if(a&&s.completed){let result=a.cash_after!==null?'Касса '+money(a.cash_after):a.action==='vote'?'Голос: '+({yes:'ЗА',no:'ПРОТИВ',abstain:'ВОЗДЕРЖАЛСЯ'})[a.params.choice]:'Ход записан';if(a.goods_after!==null)result+=' · товар '+a.goods_after;if(!a.ok)result='Отказ: '+a.err;text(result,x+20,y+395,24,a.ok?PINK:'#edb3a7')}else text(s.active?'Агент выполняет действие':'Ждёт на общей временной шкале',x+20,y+395,23,PDIM)}
}
function renderParallel(t){if(t>=108){renderVictory(t);return}g.setTransform(1,0,0,1,0,0);g.fillStyle='#0b141b';g.fillRect(0,0,1920,1080);const data=statesAt(t),states=t<18?archive.agents.map((a,i)=>({actor:i,name:a.name,target:null,active:false,progress:0})):data.states;const image=StudioWorld.renderMany(states,t);
 if(t<10){header('КАРТА ОБЩЕЙ АРЕНЫ');g.drawImage(image,0,0,image.width,image.height,130,90,1560,950);for(const [key,s] of Object.entries(StudioWorld.sites)){const p=StudioWorld.project(s.x,key==='factory'?5.5:key==='law'?5:3.8,s.z),x=130+p.x/1400*1560,y=90+(p.y-130)/900*950;box(x-120,y-22,240,44,'#10212bee',10);text(s.name,x,y,30,PINK,700,'center')}box(64,948,1792,88,'#11202cef',16);text('Производят товар → торгуют → голосуют за законы',96,985,34);text('Далее: шесть видов этой же партии одновременно',96,1020,24,PDIM)}else{
 const mode=t<18?'join':t>=108?'final':'game';header(mode==='join'?'ОДНОВРЕМЕННЫЙ ВХОД / LOCAL TEST':mode==='final'?'ФИНАЛ / ПАРТИЯ №21':'РАУНД '+data.stage.round+' / '+phases[data.stage.phase]);participantIndices.forEach((actor,i)=>drawPanel(image,actor,i,states[actor],t,mode));if(mode==='join'){const sig=parallelProof.transactions.find(t=>t.instruction==='join').signature;text('LOCAL VALIDATOR · '+sig,32,1036,17,PDIM)}else{text('ПОВТОР №21 · общая фаза и время журнала · паузы сокращены',32,1036,20,PDIM)}text('Музыка: N.O.R.M. · No Church in the Wild (8 Bit Remix)',1888,1064,17,PDIM,500,'right')}
 window.parallelLastTime=t;
}
window.Parallel={render:renderParallel,statesAt,stages:stageList,proof:parallelProof,total:120,participants:participantOrder,fullMapFrame:()=>fullMapFrame(StudioWorld.renderer.domElement)};document.fonts.ready.then(()=>renderParallel(0));

if(!location.search.includes('capture=1')){
 const controls=document.createElement('div');controls.style.cssText='position:fixed;bottom:0;left:0;right:0;background:#101820ee;display:flex;gap:16px;padding:12px;color:white;align-items:center';
 controls.innerHTML='<button id="parallel-play">▶ Смотреть</button><input id="parallel-seek" type="range" min="0" max="120" step="0.1" value="0" style="flex:1"><span>2:00</span>';
 document.body.append(controls);let playing=false,time=0,last=0;const button=controls.querySelector('button'),seek=controls.querySelector('input');
 button.onclick=()=>{if(time>=120)time=0;playing=!playing;button.textContent=playing?'Ⅱ Пауза':'▶ Смотреть';last=performance.now()};
 seek.oninput=()=>{time=Number(seek.value);renderParallel(time)};
 function animate(now){if(playing){time=Math.min(120,time+(now-last)/1000);renderParallel(time);seek.value=time;if(time===120){playing=false;button.textContent='▶ Смотреть'}}last=now;requestAnimationFrame(animate)}requestAnimationFrame(animate);
}
