#!/usr/bin/env node
const {chromium}=require(process.argv[2]||'playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),{once}=require('node:events'),{createHash}=require('node:crypto');
const root=path.resolve(__dirname,'..'),out='/Users/amir/Desktop/alashi-parallel.mp4',dir='/private/tmp/alashi-parallel-review',reportPath=root+'/docs/ops/PARALLEL_VIDEO_20260906.json';fs.mkdirSync(dir,{recursive:true});
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:!process.argv.includes('--open'),args:['--autoplay-policy=no-user-gesture-required']});let leaveOpen=false;try{const page=await browser.newPage({viewport:{width:1920,height:1080}}),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url())});
if(process.argv.includes('--verify')||process.argv.includes('--open')){
 await page.goto('file:///Users/amir/Desktop/alashi-parallel-player.html');await page.waitForFunction(()=>document.querySelector('video').readyState>=2);const meta=await page.evaluate(()=>{let v=document.querySelector('video');return {width:v.videoWidth,height:v.videoHeight,duration:v.duration}});assert.equal(meta.width,1920);assert.equal(meta.height,1080);assert.ok(Math.abs(meta.duration-120)<.1);
 for(const t of [3,14,40,70,114]){await page.evaluate(t=>{document.querySelector('video').currentTime=t},t);await page.waitForFunction(()=>{let v=document.querySelector('video');return !v.seeking&&v.readyState>=2});await page.screenshot({path:dir+'/decoded-'+t+'.png'})}
 await page.evaluate(()=>{const v=document.querySelector('video');v.currentTime=0;return v.play()});await page.waitForTimeout(2200);const playback=await page.evaluate(()=>{const v=document.querySelector('video');return {time:v.currentTime,paused:v.paused,audioBytes:v.webkitAudioDecodedByteCount}});assert.ok(playback.time>1&&!playback.paused&&playback.audioBytes>0);assert.deepEqual(errors,[]);const report=JSON.parse(fs.readFileSync(reportPath));Object.assign(report,{verified:true,metadata:meta,playback});fs.writeFileSync(reportPath,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({meta,playback}));if(process.argv.includes('--open')){leaveOpen=true;console.log('Visible Chrome player is playing.');await new Promise(r=>browser.on('disconnected',r))}return;
}
await page.goto('file://'+root+'/app/alashi-parallel-demo.html?capture=1');await page.waitForFunction(()=>!!window.Parallel);await page.evaluate(()=>document.fonts.ready);
const archive=JSON.parse(fs.readFileSync(root+'/data/live/party21_90s_export.json'));const checks=await page.evaluate(()=>{const seen=new Set;let simultaneous=0;for(let t=18;t<108;t+=.05){const d=Parallel.statesAt(t);simultaneous=Math.max(simultaneous,d.states.filter(s=>s.active&&!s.completed).length);for(const s of d.states)if(s.action)seen.add(s.action.serial)}return {seen:[...seen],simultaneous,actions:Parallel.stages.flatMap(s=>s.acts),names:Parallel.participants,phases:Parallel.stages.length}});assert.equal(checks.seen.length,archive.actions.length);assert.ok(checks.simultaneous>=2);for(const a of checks.actions){const {serial,visualStart,visualDuration,...actual}=a;assert.deepEqual(actual,archive.actions[serial])}assert.equal(checks.names.length,6);
for(const t of [3,14,40,70,114]){await page.evaluate(t=>Parallel.render(t),t);await page.screenshot({path:dir+'/preview-'+t+'.png'})}assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);console.log(JSON.stringify({attempts:checks.seen.length,simultaneous:checks.simultaneous,phases:checks.phases,errors,requests}));if(process.argv.includes('--preview')){
 const joins=await page.evaluate(()=>Parallel.proof.transactions);assert.equal(joins.length,6);assert.equal(new Set(joins.map(j=>j.receipt.slot)).size,1);assert.equal(new Set(joins.map(j=>j.signature)).size,6);
 await page.goto('file://'+root+'/app/alashi-parallel-demo.html');await page.waitForFunction(()=>!!window.Parallel);await page.locator('#parallel-play').click();await page.waitForTimeout(500);await page.locator('#parallel-play').click();assert.ok(await page.evaluate(()=>parallelLastTime>0));await page.locator('#parallel-seek').fill('70');await page.locator('#parallel-seek').dispatchEvent('input');assert.equal(await page.evaluate(()=>parallelLastTime),70);assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);console.log('PASS: six join receipts, play, pause, seek, offline');return;
}
const ffmpeg='/private/tmp/alashi-cyber-env/lib/python3.14/site-packages/imageio_ffmpeg/binaries/ffmpeg-macos-x86_64-v7.1',audio='/private/tmp/alashi-norm.webm';
const ff=spawn(ffmpeg,['-hide_banner','-loglevel','error','-y','-f','image2pipe','-framerate','24','-vcodec','mjpeg','-i','pipe:0','-i',audio,'-vf','scale=in_range=pc:out_range=tv,format=yuv420p','-c:v','libx264','-preset','veryfast','-crf','19','-profile:v','main','-level','4.1','-color_range','tv','-r','24','-af','atrim=duration=120,loudnorm=I=-18:TP=-1.5:LRA=9,afade=t=in:d=0.6,afade=t=out:st=117:d=3','-c:a','aac','-b:a','192k','-ar','48000','-ac','2','-t','120','-movflags','+faststart',out],{stdio:['pipe','ignore','pipe']});let err='';ff.stderr.on('data',d=>err+=d);ff.stdin.on('error',()=>{});const done=new Promise((res,rej)=>{ff.on('error',rej);ff.on('close',c=>c===0?res():rej(Error(err)))});const started=Date.now();for(let frame=0;frame<2880;frame++){const b64=await page.evaluate(t=>{Parallel.render(t);return document.getElementById('screen').toDataURL('image/jpeg',.94).split(',')[1]},frame/24);if(!ff.stdin.write(Buffer.from(b64,'base64')))await once(ff.stdin,'drain');if(frame%120===0)console.log('Rendered '+frame+'/2880; '+Math.round((Date.now()-started)/1000)+' seconds')}ff.stdin.end();await done;assert.deepEqual(errors,[]);const bytes=fs.readFileSync(out);const report={output:out,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),frames:2880,fps:24,attempts:checks.seen.length,max_simultaneous_moving:checks.simultaneous,source:'HTTP arena party 21',join_source:'solana-local-validator receipts, slot 351',music:{title:'NO CHURCH IN THE WILD - 8 BIT REMIX - N.O.R.M.',url:'https://www.youtube.com/watch?v=8UZNRIAD2mk',sha256:createHash('sha256').update(fs.readFileSync(audio)).digest('hex')},render_seconds:(Date.now()-started)/1000,verified:false,errors,requests};fs.writeFileSync(reportPath,JSON.stringify(report,null,2)+'\n');fs.writeFileSync('/Users/amir/Desktop/alashi-parallel-player.html','<!doctype html><meta charset="utf-8"><title>Alashi · 6 агентов параллельно</title><style>body{margin:0;background:#080d12}video{width:100vw;height:100vh}</style><video controls autoplay playsinline src="alashi-parallel.mp4"></video>');console.log(JSON.stringify(report));
}finally{if(!leaveOpen)await browser.close()}})().catch(e=>{console.error('[ERROR]',e);process.exitCode=1});
