const fs=require('node:fs'),{spawn}=require('node:child_process'),{once}=require('node:events'),{createHash}=require('node:crypto'),assert=require('node:assert/strict');
module.exports=async({page,root,errors})=>{
 const ffmpeg='/private/tmp/alashi-cyber-env/lib/python3.14/site-packages/imageio_ffmpeg/binaries/ffmpeg-macos-x86_64-v7.1',tail='/private/tmp/alashi-victory-tail.mp4',base='/Users/amir/Desktop/alashi-parallel-full-map.mp4',out='/Users/amir/Desktop/alashi-aitore-globe.mp4';
 const ff=spawn(ffmpeg,['-hide_banner','-loglevel','error','-y','-f','image2pipe','-framerate','24','-vcodec','mjpeg','-i','pipe:0','-vf','scale=in_range=pc:out_range=tv,format=yuv420p','-c:v','libx264','-preset','veryfast','-crf','18','-profile:v','main','-level','4.1','-color_range','tv','-an','-t','12',tail],{stdio:['pipe','ignore','pipe']});let err='';ff.stderr.on('data',d=>err+=d);ff.stdin.on('error',()=>{});const done=new Promise((res,rej)=>{ff.on('error',rej);ff.on('close',c=>c===0?res():rej(Error(err)))});
 for(let frame=0;frame<288;frame++){const b64=await page.evaluate(t=>{Parallel.render(t);return document.getElementById('screen').toDataURL('image/jpeg',.96).split(',')[1]},108+frame/24);if(!ff.stdin.write(Buffer.from(b64,'base64')))await once(ff.stdin,'drain');if(frame%48===0)console.log('Victory '+frame+'/288 frames')}
 ff.stdin.end();await done;assert.deepEqual(errors,[]);
 const merge=spawn(ffmpeg,['-hide_banner','-loglevel','error','-y','-i',base,'-i',tail,'-filter_complex','[0:v]trim=end_frame=2592,setpts=PTS-STARTPTS[a];[1:v]trim=end_frame=288,setpts=PTS-STARTPTS[b];[a][b]concat=n=2:v=1:a=0[v]','-map','[v]','-map','0:a:0','-c:v','libx264','-preset','veryfast','-crf','19','-profile:v','main','-level','4.1','-pix_fmt','yuv420p','-color_range','tv','-c:a','copy','-t','120','-movflags','+faststart',out],{stdio:['ignore','ignore','pipe']});let mergeError='';merge.stderr.on('data',d=>mergeError+=d);await new Promise((res,rej)=>{merge.on('error',rej);merge.on('close',c=>c===0?res():rej(Error(mergeError)))});
 const reportPath=root+'/docs/ops/PARALLEL_VIDEO_20260906.json',report=JSON.parse(fs.readFileSync(reportPath)),bytes=fs.readFileSync(out);report.base_full_map_sha256=createHash('sha256').update(fs.readFileSync(base)).digest('hex');Object.assign(report,{output:out,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),verified:false,finale:{start_seconds:108,duration_seconds:12,hero:'Aitore',staged:true,archive_modified:false,visual:'Aitore standing on illuminated Earth globe with stage lighting'},errors});fs.writeFileSync(reportPath,JSON.stringify(report,null,2)+'\n');
 const player='/Users/amir/Desktop/alashi-parallel-player.html';fs.writeFileSync(player,fs.readFileSync(player,'utf8').replace('alashi-parallel-full-map.mp4','alashi-aitore-globe.mp4'));console.log(JSON.stringify({output:out,bytes:bytes.length,finale:report.finale}));
};
