#!/usr/bin/env node
const {chromium}=require(process.argv[2]||'playwright');const {readFileSync,writeFileSync,mkdirSync}=require('node:fs');const {resolve}=require('node:path');const {createHash}=require('node:crypto');const assert=require('node:assert/strict');
const output=process.argv[3]||'/Users/amir/Desktop/alashi-studio-4k.mp4',dir='/private/tmp/alashi-studio-review';mkdirSync(dir,{recursive:true});
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--autoplay-policy=no-user-gesture-required']});try{
 const page=await browser.newPage({viewport:{width:1920,height:1080},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 if(process.argv.includes('--reference')){await page.setContent('<video style="width:100%;height:100vh" src="data:video/mp4;base64,'+readFileSync('/private/tmp/alashi-keyboard-reference.mp4').toString('base64')+'"></video>');await page.waitForFunction(()=>document.querySelector('video').readyState>=1);for(const t of [1,5,10,14]){await page.evaluate(t=>document.querySelector('video').currentTime=t,t);await page.waitForFunction(()=>{const v=document.querySelector('video');return !v.seeking&&v.readyState>=2});await page.screenshot({path:dir+'/reference-'+t+'.png'})}console.log('Reference frames ready');return}
 if(process.argv.includes('--verify')){await page.setContent('<style>body{margin:0;background:#10181c}video{width:100vw;height:100vh}</style><video src="data:video/mp4;base64,'+readFileSync(output).toString('base64')+'"></video>');await page.waitForFunction(()=>document.querySelector('video').readyState>=1,null,{timeout:30000});const metadata=await page.evaluate(()=>{const v=document.querySelector('video');return {duration:v.duration,width:v.videoWidth,height:v.videoHeight}});assert.equal(metadata.width,3840);assert.equal(metadata.height,2160);assert.ok(Math.abs(metadata.duration-120)<1);for(const [name,t] of [['join',10],['factory',23.5],['market',35.5],['payout',110]]){await page.evaluate(t=>document.querySelector('video').currentTime=t,t);await page.waitForFunction(()=>{const v=document.querySelector('video');return !v.seeking&&v.readyState>=2},null,{timeout:30000});await page.screenshot({path:dir+'/decoded-'+name+'.png'})}await page.evaluate(()=>{const v=document.querySelector('video');v.currentTime=6;return v.play()});await page.waitForTimeout(1500);metadata.audioBytes=await page.evaluate(()=>document.querySelector('video').webkitAudioDecodedByteCount);assert.ok(metadata.audioBytes>0);const reportPath=resolve(__dirname,'../docs/ops/STUDIO_VIDEO_20260906.json');const report=JSON.parse(readFileSync(reportPath));Object.assign(report,{...metadata,verified:true});writeFileSync(reportPath,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(metadata));return}
 const requests=[];page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url())});await page.goto('file://'+resolve(__dirname,'../app/alashi-studio-demo.html')+'?capture=1');await page.waitForFunction(()=>!!window.Studio,null,{timeout:30000});await page.evaluate(()=>document.fonts.ready);
 const proof=JSON.parse(readFileSync(resolve(__dirname,'../docs/ops/STUDIO_LOCAL_PROOF_20260906.json'))),embedded=await page.evaluate(()=>Studio.proof);assert.deepEqual(embedded.transactions,proof.transactions.filter(t=>['join','settle'].includes(t.instruction)));
 const states=await page.evaluate(()=>Studio.joinStates(1));assert.equal(states.length,6);assert.ok(states.every(x=>x.confirmed));assert.equal(new Set(states.map(s=>s.slot)).size,1);assert.equal(new Set(states.map(s=>s.signature)).size,6);assert.ok((await page.evaluate(()=>Studio.joinStates(.01))).every(x=>x.submitted&&!x.confirmed));
 const coverage=await page.evaluate(()=>({names:[...new Set(Studio.picks.map(s=>archive.agents[s.a.actor].name))],count:Studio.picks.length,three:THREE.REVISION,materials:[...new Set(Studio.world.scene.children.filter(x=>x.isMesh).map(x=>x.material.type))]}));assert.equal(coverage.names.length,6);assert.equal(coverage.count,14);assert.equal(await page.evaluate(()=>Studio.picks.at(-1).a.round),6);
 for(const [name,t] of [['overview',3],['join',10],['factory',23.5],['market',35.5],['parliament',27],['payout',110]]){await page.evaluate(t=>Studio.render(t),t);await page.screenshot({path:dir+'/'+name+'.png'})}
 assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);
 const bench=await page.evaluate(()=>{const start=performance.now();for(let i=0;i<24;i++)Studio.render(20+i/24);return {fps:24000/(performance.now()-start),drawCalls:Studio.world.renderer.info.render.calls,triangles:Studio.world.renderer.info.render.triangles}});console.log(JSON.stringify({preview:true,...coverage,...bench,errors,requests}));
 const replay=JSON.parse(readFileSync(resolve(__dirname,'../data/live/party21_90s_export.json')));const actions=await page.evaluate(()=>Studio.picks.map(s=>s.a));for(const a of actions)assert.ok(replay.actions.some(real=>JSON.stringify(real)===JSON.stringify(a)),'Each displayed action must match archive');
 const saved=await page.evaluate(()=>Studio.proof);assert.deepEqual(saved,embedded);
 if(process.argv.includes('--preview')){
  await page.goto('file://'+resolve(__dirname,'../app/alashi-studio-demo.html'));await page.waitForFunction(()=>!!window.Studio);await page.locator('#studio-play').click();await page.waitForTimeout(500);await page.locator('#studio-play').click();assert.ok(await page.evaluate(()=>studioLastTime>0));await page.locator('#studio-seek').fill('35');await page.locator('#studio-seek').dispatchEvent('input');assert.equal(await page.evaluate(()=>studioLastTime),35);await page.mouse.move(600,500);await page.mouse.down();await page.mouse.move(650,500);await page.mouse.up();assert.notEqual(await page.evaluate(()=>Studio.world.view.orbit),0);await page.mouse.wheel(0,-100);assert.ok(await page.evaluate(()=>Studio.world.view.zoom>1));await page.locator('#studio-reset').click();assert.deepEqual(await page.evaluate(()=>Studio.world.view),{orbit:0,zoom:1});assert.equal(await page.evaluate(()=>studioLastTime),0);assert.deepEqual(errors,[]);console.log('PASS: playback, pause, seek, orbit, zoom, reset; original archive actions retained');return;
 }

 const {spawn,execFileSync}=require('node:child_process'),{once}=require('node:events');
 const ffmpeg=process.env.ALASHI_FFMPEG||execFileSync(process.env.ALASHI_PYTHON||'/private/tmp/alashi-cyber-env/bin/python',['-c','import imageio_ffmpeg; print(imageio_ffmpeg.get_ffmpeg_exe())'],{encoding:'utf8'}).trim();
 const rate=44100,length=120*rate,wav=Buffer.alloc(44+length*2);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(rate,24);wav.writeUInt32LE(rate*2,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(length*2,40);
 for(const at of [6.52,102.5])for(let n=0;n<rate*.2;n++){const t=n/rate,env=t<.01?t/.01:Math.exp(-(t-.01)*30);wav.writeInt16LE(Math.round(Math.sin(2*Math.PI*660*t)*env*.035*32767),44+(Math.round(at*rate)+n)*2)}
 const audioPath=dir+'/confirmation.wav';writeFileSync(audioPath,wav);
 const ff=spawn(ffmpeg,['-hide_banner','-loglevel','warning','-y','-f','image2pipe','-framerate','24','-vcodec','mjpeg','-i','pipe:0','-i',audioPath,'-c:v','libx264','-preset','veryfast','-crf','20','-pix_fmt','yuv420p','-r','24','-c:a','aac','-b:a','96k','-t','120','-movflags','+faststart',output],{stdio:['pipe','ignore','pipe']});let fferr='';ff.stderr.on('data',d=>fferr=(fferr+d).slice(-8000));ff.stdin.on('error',()=>{});const finished=new Promise((res,rej)=>{ff.on('error',rej);ff.on('close',code=>code===0?res():rej(Error('FFmpeg '+code+': '+fferr)))});const started=Date.now();
 for(let frame=0;frame<2880;frame++){
  const b64=await page.evaluate(t=>{Studio.render(t);return document.getElementById('screen').toDataURL('image/jpeg',.94).split(',')[1]},frame/24);
  if(!ff.stdin.write(Buffer.from(b64,'base64')))await once(ff.stdin,'drain');
  if(frame%120===0)console.log('Rendered '+frame+' / 2880 frames; '+Math.round((Date.now()-started)/1000)+'s elapsed');
 }
 ff.stdin.end();await finished;assert.deepEqual(errors,[]);const bytes=readFileSync(output),statesFinal=await page.evaluate(()=>Studio.joinStates(1));const report={output,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),frames:2880,frame_rate:24,export_mode:'offline deterministic frames',render_seconds:(Date.now()-started)/1000,verified:false,proof_transactions:proof.transactions.length,join_slots:[...new Set(statesFinal.map(s=>s.slot))],join_submission_spread_ms:1000*(Math.max(...proof.transactions.filter(t=>t.instruction==='join').map(t=>t.submitted_at))-Math.min(...proof.transactions.filter(t=>t.instruction==='join').map(t=>t.submitted_at))),gameplay_seconds:84,gameplay_source:'HTTP arena party 21',background_music:false,errors};writeFileSync(resolve(__dirname,'../docs/ops/STUDIO_VIDEO_20260906.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));

 }finally{await browser.close()}})().catch(e=>{console.error('[ERROR]',e);process.exitCode=1});
