const studioProof=__STUDIO_PROOF__;
const studioJoins=studioProof.players.map(p=>studioProof.transactions.find(x=>x.instruction==='join'&&x.receipt.transaction.message.accountKeys[0]===p.wallet));
const joinOrigin=Math.min(...studioJoins.map(j=>j.submitted_at));
const studioPicks=[['Aibot','produce'],['Botagul','vote'],['Zhambyl','sell'],['Aitore','shuttle'],['Aikorkem','shuttle'],['Aisultan','produce'],['Aisultan','sell_credit'],['Zhambyl','inspect_license'],['Aibot','bid_license'],['Zhambyl','bid_license'],['Aitore','buy_hard'],['Aikorkem','buy_hard'],['Aisultan','sell'],['Botagul','sell']].map(([name,action],i)=>scenes[i>=12?'findLast':'find'](s=>s.a?.actor===archive.agents.findIndex(a=>a.name===name)&&s.a.action===action&&s.a.ok)).sort((a,b)=>a.serial-b.serial);
if(studioPicks.some(x=>!x))throw Error('Missing archive highlight');
C.width=3840;C.height=2160;
const studioInk='#e5eceb',studioDim='#a6b5ba',studioMint='#9adcd1';
function text(t,x,y,size=32,color=studioInk,weight=600,align='left'){g.save();g.font=weight+' '+size+'px '+(/\d|SOL/.test(String(t))?'Menlo,monospace':'Jura,sans-serif');g.fillStyle=color;g.textAlign=align;g.textBaseline='middle';g.fillText(String(t),x,y);g.restore()}
function box(x,y,w,h,fill,r=16,stroke=null){g.save();g.beginPath();g.roundRect(x,y,w,h,r);g.fillStyle=fill;g.fill();if(stroke){g.strokeStyle=stroke;g.lineWidth=1.5;g.stroke()}g.restore()}
function panel(x,y,w,h){box(x,y,w,h,'#142128ed',20,'#48606a88')}
function smallSig(sig,x,y,size=18){for(let i=0;i<sig.length;i+=44)text(sig.slice(i,i+44),x,y+Math.floor(i/44)*(size+10),size,studioMint,500)}
function labels(actor,target){
 const occupied=[];
 for(const [name,s] of Object.entries(StudioWorld.sites)){const pt=StudioWorld.project(s.x,name==='law'?5.3:name==='factory'?5.4:3.8,s.z),active=name===target;box(pt.x-92,pt.y-18,184,36,active?'#d4e8de':'#102027df',8);text(s.name,pt.x,pt.y,active?25:21,active?'#14272d':studioInk,700,'center');occupied.push(pt)}
 if(actor!==null){const a=StudioWorld.agents[actor],anchor=StudioWorld.project(a.position.x,2.3,a.position.z),candidates=[[0,-24],[0,-80],[180,-24],[-180,-24],[0,-136]].map(([dx,dy])=>({x:Math.max(112,Math.min(1288,anchor.x+dx)),y:Math.max(180,Math.min(854,anchor.y+dy))})),pt=candidates.find(v=>occupied.every(q=>Math.abs(v.x-q.x)>=190||Math.abs(v.y-q.y)>=48))||candidates[1];g.strokeStyle=studioMint;g.lineWidth=2;g.beginPath();g.moveTo(anchor.x,anchor.y+10);g.lineTo(pt.x,pt.y+22);g.stroke();box(pt.x-96,pt.y-22,192,44,'#e0eee8',10);text(archive.agents[actor].name,pt.x,pt.y,30,'#10232b',700,'center')}
 archive.agents.forEach((a,i)=>{const x=64+i*216,active=i===actor;box(x,910,200,42,active?'#d4e8de':'#12232de8',10);text(a.name,x+100,931,25,active?'#10232b':studioInk,700,'center')})
}
function world(actor,target,p,t){g.fillStyle='#10181c';g.fillRect(0,0,1920,1080);g.drawImage(StudioWorld.render(actor,target,p,t),0,130,1400,900);labels(actor,target)}
function header(sub,source){text('ALASHI',64,64,52,studioInk,700);text(sub,336,64,28,studioDim);text(source,1856,64,20,studioDim,500,'right');g.fillStyle='#77929e44';g.fillRect(64,112,1792,1)}
function overview(t){world(null,null,0,t);header('АРЕНА АГЕНТОВ','ПОВТОР ПАРТИИ №21');text('Шесть агентов.',1408,264,42,studioInk);text('Одна экономика.',1408,320,38,studioDim);archive.agents.forEach((a,i)=>{text(String(i+1).padStart(2,'0'),1408,440+i*64,24,studioDim);text(a.name,1472,440+i*64,32,studioInk)});text('Рынок → действие → закон',64,1000,30,studioInk)}
function joinStates(t){return studioProof.players.map((p,i)=>({name:p.name,wallet:p.wallet,signature:studioJoins[i].signature,slot:studioJoins[i].receipt.slot,submitted:t>=studioJoins[i].submitted_at-joinOrigin,confirmed:t>=studioJoins[i].confirmed_at-joinOrigin}))}
function concurrentJoin(t){world(null,null,0,6+t);g.fillStyle='#081218d9';g.fillRect(0,130,1920,900);header('ШЕСТЬ АГЕНТОВ ВХОДЯТ ВМЕСТЕ','LOCAL VALIDATOR / ТЕСТОВАЯ ПАРТИЯ');const states=joinStates(t);text('6 кошельков → одна арена',64,190,52,studioInk);text('Взнос каждого: 0.010 SOL',1856,190,28,studioMint,600,'right');states.forEach((p,i)=>{const x=64+(i%3)*608,y=288+Math.floor(i/3)*304;panel(x,y,576,272);text(p.name,x+24,y+40,40,studioInk,700);text(p.confirmed?'CONFIRMED':'SUBMITTED',x+552,y+40,19,p.confirmed?studioMint:studioDim,700,'right');text(p.wallet,x+24,y+100,18,studioDim,500);smallSig(p.signature,x+24,y+156,18);text('SLOT '+p.slot+' · 1 SIGNER',x+24,y+234,20,studioMint,600)});text(states.every(s=>s.confirmed)?'Все 6 входов подтверждены в одном слоте':'Отправляем 6 подписанных входов одновременно',64,964,34,studioInk);text('RPC-квитанции · отдельная локальная проверка',64,1012,24,studioDim)}
function gameplay(s,p,t){const a=s.a,[title,target]=info[a.action],agent=archive.agents[a.actor];world(a.actor,target,p,t);header('РАУНД '+a.round+' / '+phases[a.phase],'HTTP ARENA / ПАРТИЯ №21');panel(1408,176,448,728);text('СЕЙЧАС ХОДИТ',1440,216,22,studioDim);text(agent.name,1440,280,52,studioInk,700);text('→ '+StudioWorld.sites[target].name,1440,344,28,studioMint);wrap(title,1440,416,380,36,studioInk);const q=a.params;let detail=q.units!==undefined?q.units+' товара':a.action==='vote'?({yes:'За',no:'Против',abstain:'Воздержался'})[q.choice]:q.amount!==undefined?money(q.amount):a.action==='shuttle'?'Поездка за товаром':a.action==='produce'?'Выпуск товара':'Решение из журнала';text(detail,1440,500,28,studioDim);text(p<.58?'АГЕНТ ДЕЙСТВУЕТ':'ХОД ПРИНЯТ',1440,568,25,p<.58?studioDim:studioMint);if(p>=.58){if(a.cash_after!==null){text('КАССА ПОСЛЕ ХОДА',1440,656,20,studioDim);text(money(a.cash_after),1440,704,46,studioInk)}if(a.goods_after!==null)text('Товар: '+a.goods_after,1440,776,30,studioInk);if(a.action==='vote')text('Вес голоса = влияние',1440,680,24,studioDim)}text('ХОД '+s.serial+' / '+archive.actions.length,1440,856,22,studioDim);box(64,968,1792,64,'#142128ed',16);text(agent.name+' → '+StudioWorld.sites[target].name+' · '+title,96,1000,30,studioInk);g.fillStyle=studioMint;g.fillRect(96,1020,1728*p,3)}
function studioPayout(t){world(null,null,0,102+t);g.fillStyle='#081218ec';g.fillRect(0,130,1920,900);header('РАСЧЁТ ЗАВЕРШЁН','LOCAL VALIDATOR / ТЕСТОВАЯ ПАРТИЯ');text('Банк распределён',64,208,60,studioInk);const ordered=[...studioProof.players].sort((a,b)=>(studioProof.payouts.find(p=>p.wallet===b.wallet)?.amount||0)-(studioProof.payouts.find(p=>p.wallet===a.wallet)?.amount||0));ordered.forEach((who,i)=>{const pay=studioProof.payouts.find(p=>p.wallet===who.wallet),x=64+(i%3)*608,y=304+Math.floor(i/3)*168;panel(x,y,576,144);text(who.name,x+24,y+36,32,studioInk);text(pay?(pay.amount/1e9).toFixed(5)+' SOL':'0 SOL',x+24,y+92,44,pay?studioMint:studioDim)});const tx=studioProof.transactions.find(x=>x.instruction==='settle');smallSig(tx.signature,64,744,26);text('TX CONFIRMED · SLOT '+tx.receipt.slot,64,864,30,studioMint);text('0.060 SOL = 0.057 выплаты + 0.003 рейк',64,952,30,studioInk);text('Это локальная проверка контракта, не выплата HTTP-партии №21.',64,1012,24,studioDim)}
function renderStudio(t){g.setTransform(2,0,0,2,0,0);t=Math.max(0,Math.min(120,t));if(t<6)overview(t);else if(t<18)concurrentJoin(t-6);else if(t<102){const n=Math.min(13,Math.floor((t-18)/6));gameplay(studioPicks[n],((t-18)%6)/6,t)}else if(t<118)studioPayout(t-102);else{overview(t);text('github.com/Jakisheff/alashi',1408,936,24,studioMint)}window.studioLastTime=t}
async function studioAudio(){const off=new OfflineAudioContext(1,120*44100,44100);for(const at of [6.52,102.5]){const o=off.createOscillator(),v=off.createGain();o.frequency.value=660;v.gain.setValueAtTime(0,at);v.gain.linearRampToValueAtTime(.035,at+.01);v.gain.exponentialRampToValueAtTime(.0001,at+.2);o.connect(v);v.connect(off.destination);o.start(at);o.stop(at+.2)}return off.startRendering()}
window.Studio={render:renderStudio,proof:studioProof,picks:studioPicks,joinStates,total:120,prepareAudio:studioAudio,world:StudioWorld};
document.fonts.ready.then(()=>renderStudio(0));

if(!new URLSearchParams(location.search).has('capture')){
 let at=0,paused=true,previous=performance.now();const controls=document.createElement('div');controls.id='studio-controls';controls.style.cssText='position:fixed;bottom:12px;left:50%;transform:translateX(-50%);display:flex;gap:12px;padding:10px 16px;background:#10212eee;border:1px solid #59747c;border-radius:12px;color:#edf4f1;font:16px sans-serif';controls.innerHTML='<button id="studio-play">▶ Смотреть</button><button id="studio-reset">В начало</button><input id="studio-seek" aria-label="Время повтора" type="range" min="0" max="120" step="0.1" value="0"><span>Поворот: мышь · масштаб: колесо</span>';document.body.appendChild(controls);const play=controls.querySelector('#studio-play'),seek=controls.querySelector('#studio-seek');function sync(){play.textContent=paused?'▶ Смотреть':'Ⅱ Пауза';seek.value=at}play.onclick=()=>{paused=!paused;if(at>=120)at=0;sync()};controls.querySelector('#studio-reset').onclick=()=>{at=0;StudioWorld.view.orbit=0;StudioWorld.view.zoom=1;renderStudio(at);sync()};seek.oninput=()=>{at=Number(seek.value);renderStudio(at)};let drag=null;C.addEventListener('pointerdown',e=>{drag=e.clientX;C.setPointerCapture(e.pointerId)});C.addEventListener('pointermove',e=>{if(drag!==null){StudioWorld.view.orbit=Math.max(-.5,Math.min(.5,StudioWorld.view.orbit+(e.clientX-drag)*.004));drag=e.clientX;renderStudio(at)}});C.addEventListener('pointerup',()=>drag=null);C.addEventListener('pointercancel',()=>drag=null);C.addEventListener('wheel',e=>{e.preventDefault();StudioWorld.view.zoom=Math.max(.8,Math.min(1.3,StudioWorld.view.zoom-e.deltaY*.001));renderStudio(at)},{passive:false});function tickStudio(now){if(!paused){at=Math.min(120,at+(now-previous)/1000);renderStudio(at);if(at>=120)paused=true;sync()}previous=now;requestAnimationFrame(tickStudio)}requestAnimationFrame(tickStudio)
}
